CINE 3) Comedias Españolas
10
25
Torrente
Atraco a las tres
Historias de la puta mili
La Vaquilla
Cateto a babor
Sor Citroen
El otro lado de la cama
El oro de moscu
Jenaro el de los 14
Bienvenido Mister Marshall
Se llama Jose Luis
Va de un atraco
De "sordados"
Una buena obra sobre la guerra
Con A. Landa y de marineros
Eterna pelicula
Magnífica comedia-musical
Reciente actuación de Bonilla
Un clásico rodado en 1970. Con Landa.
Una gran obra de Berlanga.
