CINE 4) Peliculas bélicas
10
25
Platoon
La chaqueta metalica
Corazones de hierro
Nacido el 4 de Julio
Salvar al Soldado Ryan
La delgada linea roja
Apocalipsis Now
K-19
Stalingrado
Doce del patibulo
Un éxito sobre Vietnam
Una de las mejores de M.J. Fox
Tom Cruise es un soldado
Ambientada en la II Guerra
Otra sobre la II Guerra.
Eterno Marlon Brando
Submarino de CCCP
Va sobre una batalla
Un clásico bélico