CINE 2) Actrices españolas
10
25
Carmen Maura
Paz Vega
Marisol
Elsa Pataky
Belen Rueda
Ariadna Gil
Gracita Morales
Maribel Verdu
Pilar Lopez de Ayala
Candela Peña
Musa de Almodóvar
Conocida en algun lado de la cama
Archiconocida de nuestro cine
Fue dirigida por Garci
Una serrana
Una de Belle Epoque
Sor Citroën
Otra madrileña de Belle Epoque
Trabaja con muchas (7) vidas
Recibio el Goya por "Te doy mis ojos"